api_platform:
  title: 'API Inthebox'
  description: 'API de l application mobile INTHEBOX'
  version: '1.0.0'
  show_webby: false
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  oauth:
    # To enable or disable OAuth.
    enabled: false